version: "3.9"
services:
  artemis:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ARTEMIS_USERNAME: "${ARTEMIS_USERNAME:-admin}"
      ARTEMIS_PASSWORD: "${ARTEMIS_PASSWORD:-admin}"