server:
  port: 8080

spring:
  application:
    name: camelDemo
  artemis:
    user: admin
    password: admin
    host: localhost
    port: 61616
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/song_pdb
    username: camel
    password: camel_password
    driver-class-name: oracle.jdbc.driver.OracleDriver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    auto-startup: false
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true
  cache:
    jcache:
      config: classpath:ehcache.xml

camel:
  component:
    quartz2:
      scheduler: "quartzScheduler"