CREATE SEQUENCE  "CAMEL"."SONG_PLAY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 701 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table QRTZ_BLOB_TRIGGERS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_BLOB_TRIGGERS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "TRIGGER_NAME" VARCHAR2(200 BYTE),
     "TRIGGER_GROUP" VARCHAR2(200 BYTE),
     "BLOB_DATA" BLOB
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS"
 LOB ("BLOB_DATA") STORE AS SECUREFILE (
  TABLESPACE "SONG_PDB_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table QRTZ_CALENDARS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_CALENDARS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "CALENDAR_NAME" VARCHAR2(200 BYTE),
     "CALENDAR" BLOB
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS"
 LOB ("CALENDAR") STORE AS SECUREFILE (
  TABLESPACE "SONG_PDB_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table QRTZ_CRON_TRIGGERS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_CRON_TRIGGERS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "TRIGGER_NAME" VARCHAR2(200 BYTE),
     "TRIGGER_GROUP" VARCHAR2(200 BYTE),
     "CRON_EXPRESSION" VARCHAR2(120 BYTE),
     "TIME_ZONE_ID" VARCHAR2(80 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Table QRTZ_FIRED_TRIGGERS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "ENTRY_ID" VARCHAR2(95 BYTE),
     "TRIGGER_NAME" VARCHAR2(200 BYTE),
     "TRIGGER_GROUP" VARCHAR2(200 BYTE),
     "INSTANCE_NAME" VARCHAR2(200 BYTE),
     "FIRED_TIME" NUMBER(13,0),
     "SCHED_TIME" NUMBER(13,0),
     "PRIORITY" NUMBER(13,0),
     "STATE" VARCHAR2(16 BYTE),
     "JOB_NAME" VARCHAR2(200 BYTE),
     "JOB_GROUP" VARCHAR2(200 BYTE),
     "IS_NONCONCURRENT" VARCHAR2(1 BYTE),
     "REQUESTS_RECOVERY" VARCHAR2(1 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Table QRTZ_JOB_DETAILS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_JOB_DETAILS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "JOB_NAME" VARCHAR2(200 BYTE),
     "JOB_GROUP" VARCHAR2(200 BYTE),
     "DESCRIPTION" VARCHAR2(250 BYTE),
     "JOB_CLASS_NAME" VARCHAR2(250 BYTE),
     "IS_DURABLE" VARCHAR2(1 BYTE),
     "IS_NONCONCURRENT" VARCHAR2(1 BYTE),
     "IS_UPDATE_DATA" VARCHAR2(1 BYTE),
     "REQUESTS_RECOVERY" VARCHAR2(1 BYTE),
     "JOB_DATA" BLOB
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS"
 LOB ("JOB_DATA") STORE AS SECUREFILE (
  TABLESPACE "SONG_PDB_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table QRTZ_LOCKS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_LOCKS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "LOCK_NAME" VARCHAR2(40 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Table QRTZ_PAUSED_TRIGGER_GRPS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_PAUSED_TRIGGER_GRPS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "TRIGGER_GROUP" VARCHAR2(200 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Table QRTZ_SCHEDULER_STATE
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_SCHEDULER_STATE"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "INSTANCE_NAME" VARCHAR2(200 BYTE),
     "LAST_CHECKIN_TIME" NUMBER(13,0),
     "CHECKIN_INTERVAL" NUMBER(13,0)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Table QRTZ_SIMPLE_TRIGGERS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "TRIGGER_NAME" VARCHAR2(200 BYTE),
     "TRIGGER_GROUP" VARCHAR2(200 BYTE),
     "REPEAT_COUNT" NUMBER(7,0),
     "REPEAT_INTERVAL" NUMBER(12,0),
     "TIMES_TRIGGERED" NUMBER(10,0)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Table QRTZ_SIMPROP_TRIGGERS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_SIMPROP_TRIGGERS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "TRIGGER_NAME" VARCHAR2(200 BYTE),
     "TRIGGER_GROUP" VARCHAR2(200 BYTE),
     "STR_PROP_1" VARCHAR2(512 BYTE),
     "STR_PROP_2" VARCHAR2(512 BYTE),
     "STR_PROP_3" VARCHAR2(512 BYTE),
     "INT_PROP_1" NUMBER(10,0),
     "INT_PROP_2" NUMBER(10,0),
     "LONG_PROP_1" NUMBER(13,0),
     "LONG_PROP_2" NUMBER(13,0),
     "DEC_PROP_1" NUMBER(13,4),
     "DEC_PROP_2" NUMBER(13,4),
     "BOOL_PROP_1" VARCHAR2(1 BYTE),
     "BOOL_PROP_2" VARCHAR2(1 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Table QRTZ_TRIGGERS
--------------------------------------------------------

CREATE TABLE "CAMEL"."QRTZ_TRIGGERS"
(	"SCHED_NAME" VARCHAR2(120 BYTE),
     "TRIGGER_NAME" VARCHAR2(200 BYTE),
     "TRIGGER_GROUP" VARCHAR2(200 BYTE),
     "JOB_NAME" VARCHAR2(200 BYTE),
     "JOB_GROUP" VARCHAR2(200 BYTE),
     "DESCRIPTION" VARCHAR2(250 BYTE),
     "NEXT_FIRE_TIME" NUMBER(13,0),
     "PREV_FIRE_TIME" NUMBER(13,0),
     "PRIORITY" NUMBER(13,0),
     "TRIGGER_STATE" VARCHAR2(16 BYTE),
     "TRIGGER_TYPE" VARCHAR2(8 BYTE),
     "START_TIME" NUMBER(13,0),
     "END_TIME" NUMBER(13,0),
     "CALENDAR_NAME" VARCHAR2(200 BYTE),
     "MISFIRE_INSTR" NUMBER(2,0),
     "JOB_DATA" BLOB
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "SONG_PDB_TBS"
 LOB ("JOB_DATA") STORE AS SECUREFILE (
  TABLESPACE "SONG_PDB_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SONG_PLAY
--------------------------------------------------------

CREATE TABLE "CAMEL"."SONG_PLAY"
(	"ID" NUMBER(19,0),
     "DURATION_MS" NUMBER(19,0),
     "SONG_ID" NUMBER(19,0),
     "USER_ID" NUMBER(19,0),
     "REVIEW_TEXT" VARCHAR2(255 CHAR)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_C
--------------------------------------------------------

CREATE INDEX "CAMEL"."IDX_QRTZ_T_C" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "CALENDAR_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_CRON_TRIG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_CRON_TRIG_PK" ON "CAMEL"."QRTZ_CRON_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_FT_TRIG_INST_NAME
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_FT_TRIG_INST_NAME" ON "CAMEL"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME", "INSTANCE_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_J
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_J" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_JG
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_JG" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "JOB_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_SIMPLE_TRIG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_SIMPLE_TRIG_PK" ON "CAMEL"."QRTZ_SIMPLE_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_LOCKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_LOCKS_PK" ON "CAMEL"."QRTZ_LOCKS" ("SCHED_NAME", "LOCK_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_J_REQ_RECOVERY
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_J_REQ_RECOVERY" ON "CAMEL"."QRTZ_JOB_DETAILS" ("SCHED_NAME", "REQUESTS_RECOVERY")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_J_GRP
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_J_GRP" ON "CAMEL"."QRTZ_JOB_DETAILS" ("SCHED_NAME", "JOB_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_N_STATE
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_N_STATE" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP", "TRIGGER_STATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_CALENDARS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_CALENDARS_PK" ON "CAMEL"."QRTZ_CALENDARS" ("SCHED_NAME", "CALENDAR_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_N_G_STATE
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_N_G_STATE" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_GROUP", "TRIGGER_STATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_NFT_ST_MISFIRE_GRP
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_NFT_ST_MISFIRE_GRP" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "MISFIRE_INSTR", "NEXT_FIRE_TIME", "TRIGGER_GROUP", "TRIGGER_STATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_NEXT_FIRE_TIME
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_NEXT_FIRE_TIME" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "NEXT_FIRE_TIME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_NFT_MISFIRE
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_NFT_MISFIRE" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "MISFIRE_INSTR", "NEXT_FIRE_TIME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_TRIGGERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_TRIGGERS_PK" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_FT_J_G
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_FT_J_G" ON "CAMEL"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_G
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_G" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_FT_T_G
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_FT_T_G" ON "CAMEL"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_JOB_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_JOB_DETAILS_PK" ON "CAMEL"."QRTZ_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_BLOB_TRIG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_BLOB_TRIG_PK" ON "CAMEL"."QRTZ_BLOB_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_PAUSED_TRIG_GRPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_PAUSED_TRIG_GRPS_PK" ON "CAMEL"."QRTZ_PAUSED_TRIGGER_GRPS" ("SCHED_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_NFT_ST_MISFIRE
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_NFT_ST_MISFIRE" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "MISFIRE_INSTR", "NEXT_FIRE_TIME", "TRIGGER_STATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_FT_JG
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_FT_JG" ON "CAMEL"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME", "JOB_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_FIRED_TRIGGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_FIRED_TRIGGER_PK" ON "CAMEL"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME", "ENTRY_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_FT_TG
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_FT_TG" ON "CAMEL"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_FT_INST_JOB_REQ_RCVRY
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_FT_INST_JOB_REQ_RCVRY" ON "CAMEL"."QRTZ_FIRED_TRIGGERS" ("SCHED_NAME", "INSTANCE_NAME", "REQUESTS_RECOVERY")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_NFT_ST
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_NFT_ST" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_STATE", "NEXT_FIRE_TIME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index IDX_QRTZ_T_STATE
--------------------------------------------------------

  CREATE INDEX "CAMEL"."IDX_QRTZ_T_STATE" ON "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_STATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_SCHEDULER_STATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_SCHEDULER_STATE_PK" ON "CAMEL"."QRTZ_SCHEDULER_STATE" ("SCHED_NAME", "INSTANCE_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  DDL for Index QRTZ_SIMPROP_TRIG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEL"."QRTZ_SIMPROP_TRIG_PK" ON "CAMEL"."QRTZ_SIMPROP_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS" ;
--------------------------------------------------------
--  Constraints for Table QRTZ_SIMPLE_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" MODIFY ("TRIGGER_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" MODIFY ("TRIGGER_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" MODIFY ("REPEAT_COUNT" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" MODIFY ("REPEAT_INTERVAL" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" MODIFY ("TIMES_TRIGGERED" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" ADD CONSTRAINT "QRTZ_SIMPLE_TRIG_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_CRON_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_CRON_TRIGGERS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_CRON_TRIGGERS" MODIFY ("TRIGGER_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_CRON_TRIGGERS" MODIFY ("TRIGGER_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_CRON_TRIGGERS" MODIFY ("CRON_EXPRESSION" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_CRON_TRIGGERS" ADD CONSTRAINT "QRTZ_CRON_TRIG_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_PAUSED_TRIGGER_GRPS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_PAUSED_TRIGGER_GRPS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_PAUSED_TRIGGER_GRPS" MODIFY ("TRIGGER_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_PAUSED_TRIGGER_GRPS" ADD CONSTRAINT "QRTZ_PAUSED_TRIG_GRPS_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_SIMPROP_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_SIMPROP_TRIGGERS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPROP_TRIGGERS" MODIFY ("TRIGGER_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPROP_TRIGGERS" MODIFY ("TRIGGER_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SIMPROP_TRIGGERS" ADD CONSTRAINT "QRTZ_SIMPROP_TRIG_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_BLOB_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_BLOB_TRIGGERS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_BLOB_TRIGGERS" MODIFY ("TRIGGER_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_BLOB_TRIGGERS" MODIFY ("TRIGGER_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_BLOB_TRIGGERS" ADD CONSTRAINT "QRTZ_BLOB_TRIG_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_SCHEDULER_STATE
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_SCHEDULER_STATE" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SCHEDULER_STATE" MODIFY ("INSTANCE_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SCHEDULER_STATE" MODIFY ("LAST_CHECKIN_TIME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SCHEDULER_STATE" MODIFY ("CHECKIN_INTERVAL" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_SCHEDULER_STATE" ADD CONSTRAINT "QRTZ_SCHEDULER_STATE_PK" PRIMARY KEY ("SCHED_NAME", "INSTANCE_NAME")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_LOCKS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_LOCKS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_LOCKS" MODIFY ("LOCK_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_LOCKS" ADD CONSTRAINT "QRTZ_LOCKS_PK" PRIMARY KEY ("SCHED_NAME", "LOCK_NAME")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SONG_PLAY
--------------------------------------------------------

ALTER TABLE "CAMEL"."SONG_PLAY" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."SONG_PLAY" ADD PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_JOB_DETAILS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("JOB_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("JOB_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("JOB_CLASS_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("IS_DURABLE" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("IS_NONCONCURRENT" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("IS_UPDATE_DATA" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" MODIFY ("REQUESTS_RECOVERY" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_JOB_DETAILS" ADD CONSTRAINT "QRTZ_JOB_DETAILS_PK" PRIMARY KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_FIRED_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("ENTRY_ID" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("TRIGGER_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("TRIGGER_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("INSTANCE_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("FIRED_TIME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("SCHED_TIME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("PRIORITY" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" MODIFY ("STATE" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_FIRED_TRIGGERS" ADD CONSTRAINT "QRTZ_FIRED_TRIGGER_PK" PRIMARY KEY ("SCHED_NAME", "ENTRY_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("TRIGGER_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("TRIGGER_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("JOB_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("JOB_GROUP" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("TRIGGER_STATE" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("TRIGGER_TYPE" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" MODIFY ("START_TIME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" ADD CONSTRAINT "QRTZ_TRIGGERS_PK" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QRTZ_CALENDARS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_CALENDARS" MODIFY ("SCHED_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_CALENDARS" MODIFY ("CALENDAR_NAME" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_CALENDARS" MODIFY ("CALENDAR" NOT NULL ENABLE);
ALTER TABLE "CAMEL"."QRTZ_CALENDARS" ADD CONSTRAINT "QRTZ_CALENDARS_PK" PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "SONG_PDB_TBS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QRTZ_BLOB_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_BLOB_TRIGGERS" ADD CONSTRAINT "QRTZ_BLOB_TRIG_TO_TRIG_FK" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    REFERENCES "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QRTZ_CRON_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_CRON_TRIGGERS" ADD CONSTRAINT "QRTZ_CRON_TRIG_TO_TRIG_FK" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    REFERENCES "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QRTZ_SIMPLE_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_SIMPLE_TRIGGERS" ADD CONSTRAINT "QRTZ_SIMPLE_TRIG_TO_TRIG_FK" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    REFERENCES "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QRTZ_SIMPROP_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_SIMPROP_TRIGGERS" ADD CONSTRAINT "QRTZ_SIMPROP_TRIG_TO_TRIG_FK" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
    REFERENCES "CAMEL"."QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QRTZ_TRIGGERS
--------------------------------------------------------

ALTER TABLE "CAMEL"."QRTZ_TRIGGERS" ADD CONSTRAINT "QRTZ_TRIGGER_TO_JOBS_FK" FOREIGN KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
    REFERENCES "CAMEL"."QRTZ_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") ENABLE;
